import { ThemeProvider } from '@/components/theme-provider'
import './globals.css'

import type { Metadata } from 'next'
import Header from './components/header'
// import { Nunito_Sans } from 'next/font/google'

// const nunitoSans = Nunito_Sans({
//   subsets: ['latin'],
// })

export const metadata: Metadata = {
  title: 'Rest Countries API',
  description: 'Generated by Muhammad Ali Haider',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body
        className={` bg-lightBG dark:bg-mainDarkBG antialiased min-h-screen flex flex-col overflow-x-hidden`}
      >
        <ThemeProvider
          attribute='class'
          defaultTheme='system'
          enableSystem
          disableTransitionOnChange
        >
          <Header />
          {children}
        </ThemeProvider>
      </body>
    </html>
  )
}
